spring.datasource.url=jdbc:mysql://localhost:3306/carrentalapp
spring.datasource.username=root
spring.datasource.password=Ysm@69242

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=U3ByaW5nQm9vdENhclJlbnRhbFN5c3RlbUpXVFNlY3JldEtleUZvclRlc3RpbmcxMjM0NTY3ODkw
jwt.expiration=86400000